#!/bin/bash

# Instala las dependencias
apt-get install uuid-runtime -y

# Ejecuta el script de instalación de V2Ray
source <(curl -sL https://multi.netlify.com/v2ray.sh)

while true
do
    clear
    echo "GESTION DE USUARIOS V2RAY"
    echo "====================================================="
    echo "De momento este menú solo está"
    echo "optimizado para usuarios VMESS"
    echo "====================================================="
    echo " [1] > CREAR USUARIOS"
    echo " [2] > ELIMINAR USUARIOS"
    echo " [3] > RENOVAR USUARIO"
    echo "-----------------------------------------------------"
    echo " [4] > VMESS DE USUARIOS"
    echo " [5] > RESPALDO DE SEGURIDAD"
    echo "====================================================="
    echo " [0] > VOLVER"
    echo "====================================================="
    read -p "Seleccione una Opción: " option

    case $option in
        1)
            # Opción para CREAR USUARIOS

            # Generar un nombre de usuario automático basado en un UUID
            username=$(uuidgen)

            # Solicitar la duración en días
            read -p "Ingrese la duración en días: " days

            # Verificar si se ingresó un valor numérico
            if ! [[ $days =~ ^[0-9]+$ ]]; then
                echo "Error: La duración debe ser un número entero."
            else
                # Lógica para crear el usuario V2Ray
                v2ray_user_id=$(v2ray add -name $username -d $days)

                if [ $? -eq 0 ]; then
                    echo "Usuario V2Ray creado con éxito."
                    echo "Nombre de usuario: $username"
                    echo "ID de usuario: $v2ray_user_id"
                else
                    echo "Error al crear el usuario V2Ray."
                fi
            fi
            ;;
        2)
            # Coloca aquí el código para eliminar usuarios V2Ray
            echo "Opción 2 seleccionada: ELIMINAR USUARIOS"
            ;;
        3)
            # Coloca aquí el código para renovar usuarios V2Ray
            echo "Opción 3 seleccionada: RENOVAR USUARIO"
            ;;
        4)
            # Coloca aquí el código para ver usuarios VMESS
            echo "Opción 4 seleccionada: VMESS DE USUARIOS"
            ;;
        5)
            # Coloca aquí el código para realizar respaldo de seguridad
            echo "Opción 5 seleccionada: RESPALDO DE SEGURIDAD"
            ;;
        0)
            echo "Saliendo del menú. ¡Adiós!"
            exit
            ;;
        *)
            echo "Opción no válida. Intente de nuevo."
            ;;
    esac

    read -p "Presione Enter para continuar..."
done
      
